### ISSUE TITLE
tag the rockspec with the "neovim" label.

### ISSUE THREAD

**Issue by teto** [gennaro-tedesco/nvim-possession#20]
hi, 
could you tag tag https://luarocks.org/modules/gennaro-tedesco/nvim-possession with the label "neovim" so that it appears on
https://luarocks.org/labels/neovim. It's part of the marketing war to show that luarocks is the way to go. 

NB: you could also add it to the rockspec but it wont be picked up by luarocks.org :'( https://github.com/luarocks/luarocks-site/issues/188

**Comment by gennaro-tedesco** [comment]
Of course, I will do. Must it be done via the luarocks interface? If so, how?

**Comment by teto** [comment]
yes no choice it has to be done through luarocks.org 
![image](https://user-images.githubusercontent.com/886074/220695319-15ffc3d8-8e8e-4c26-a176-80dea1a6e61e.png)

**Comment by gennaro-tedesco** [comment]
Done, thank you for reminding! :)

**Comment by teto** [comment]
thank you for being sport ;)
