### ISSUE TITLE
I have a text on the top that I don't know how to turn off

### ISSUE THREAD

**Issue by faustozamparelli** [gennaro-tedesco/nvim-possession#41]
<img width="1413" alt="Screenshot 2024-05-20 at 15 09 43" src="https://github.com/gennaro-tedesco/nvim-possession/assets/105665123/ae680514-062f-4d44-a4d6-96c184a4ce48">
I have this prompt on the top 
'' :: <ctrl-g> to Disable .gitignore, cwd: sessions/ " how can I disable it, I don't know where it comes from.
Probably it comes from a setting of fzf-lua, if it's inappropriate I'll ask in their repo.

Thanks in advance

**Comment by gennaro-tedesco** [comment]
Good afternoon! Yes, those are headers that can be enabled/disabled via `fzf-lua` settings; if I am not mistaken you can disable them via the options
```lua
...
  cwd_header = false,
  cwd_prompt = false,
```
in the file picker for `fzf` (please double check their documentation, I might remember mistakenly).
