### ISSUE TITLE
Sessions not loading

### ISSUE THREAD

**Issue by SlartThunder** [gennaro-tedesco/nvim-possession#43]
I just upgraded nvim version and packages:
```bash
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info
```

`nvim-possession` loaded using Lazy manager:
```bash
dir     ~/.local/share/nvim/lazy/nvim-possession
url     https://github.com/gennaro-tedesco/nvim-possession
version 0.0.14
tag     v0.0.14
branch  main
commit  0844f6d
readme  README.md
help    |possession.txt|
```

The issue is that `nvim-possession` does not load the sessions anymore as it should. 
It _displays_ the session as a buffer in **neovim,**, the ones located in `~/.local/share/nvim/sessions/`

**Comment by gennaro-tedesco** [comment]
Good evening, could you please indicate some steps to reproduce the issue? In particular the steps that you understand to save the session first, and then loaded it afterwards (for instance are you loading the session automatically)?

It would also help if you could try to reproduce the problem using the [minimal repro.lua](https://github.com/gennaro-tedesco/nvim-possession/wiki#minimal-reprolua-to-reproduce-an-issue).

**Comment by SlartThunder** [comment]
At first the sesions were coming from the older version, so I thought that maybe something broke and I deleted them to start a new fresh session.
At this point, I just created a test session with 2 buffers open in a vertical split and saved the session, exited from neovim.
When entering again, I listed the sessin <leader>sl and choose the only 1 existing at this point, howeverthe session was displayed rather than load. 

Moreover, when I list the sessions, also a .DS_Store file is shown that it does not exist in location `~/.local/share/nvim/sessions/`

And most interesting, it seems fzf-lua fails with this plugin. When I tried `ctrl-g` errors pop up

This is my `nvim-possession` setup:
```lua
    require("nvim-possession").setup({
	  autoswitch = { enable = true, },
	  autosave = false,
	  post_hook = require("nvim-possession-extension").set_mappings_again,
	  fzf_winopts = {
		  preview = {
			horizontal = "up:60%",
		  },
		}
```

**Comment by gennaro-tedesco** [comment]
> And most interesting, it seems fzf-lua fails with this plugin. When I tried ctrl-g errors pop up

what is `ctrl-g` supposed to do here?

> post_hook = require("nvim-possession-extension").set_mappings_again,

what are these `require("nvim-possession-extension").set_mappings_again`?

I presume the problem may lie in some keymappings that you use for `fzf` where `enter` doesn't select the list item to source but rather displays it in a buffer. Please try with the [minimal repro](https://github.com/gennaro-tedesco/nvim-possession/wiki#minimal-reprolua-to-reproduce-an-issue) because we need to isolate if this behaviour is generated by external keymaps (notice that with the minimal repro also `fzf` is configured minimally).

**Comment by SlartThunder** [comment]
I found the issue… at least to me!

In `nvim-possession/lua/nvim-possession/init.lua` function [M.list the actions array](https://github.com/gennaro-tedesco/nvim-possession/blob/0844f6d21b358f748b4d753c91ec767517aca447/lua/nvim-possession/init.lua#L141), rather than defining "enter" I switched to "default" to make it to work.

**Comment by gennaro-tedesco** [comment]
Yes, if I remember correctly this was a change introduced in `fzf-lua` some time ago.

Glad that you solved it: can I consider this closed?

**Comment by SlartThunder** [comment]
IDK!
What should be the correct value for M.list actions? "default" or "enter"?
If I change the code on my box, I will have issues when upgrading the plugin…

**Comment by gennaro-tedesco** [comment]
As you can see from [this commit](https://github.com/gennaro-tedesco/nvim-possession/commit/755d6f270c9b9ef83a732cdc5aa3d68565cda8d6) the value was changed in the upstream fzf-lua to use "enter". Are you sure that your fzf-lua is updated to the latest?

**Comment by SlartThunder** [comment]
Yes, fzf-lua is updated to the latest. See below image:
![fzf-lua](https://github.com/user-attachments/assets/965e24ba-0bd1-4c26-8b6c-599a97a531ad)



Kind regards!
